version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
